name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Add VSTest to PATH
      uses: darenm/Setup-VSTest@v1.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Run MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild
      
    - name: Run VSTest
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: '**\\*Tests.dll'
        searchFolder: ./x64/
        runInParallel: true
